### PR TITLE
Fix typo in the API docs page for ECMAS

### PR DESCRIPTION
**Pull request by umer936**
Should I should have put the PR against the `gh-pages-develop` branch instead of `gh-pages` or is this fine?
I can do the other if so.

### CODE REVIEW

**Comment by palcarazm** [comment]
It's fine. Develop is the doc for the next release 😊.

**Comment by palcarazm** [comment]
Thanks for PR.  I merge it 🥳

**Comment by umer936** [comment]
Would you be willing to add the `Hacktoberfest-accepted` label to this PR? 

https://hacktoberfest.com/participation/#pr-mr-details

I would appreciate it so then I can get credit for this PR for Hacktoberfest. 
Thanks :)

**Comment by palcarazm** [comment]
> Would you be willing to add the `Hacktoberfest-accepted` label to this PR?
> 
> https://hacktoberfest.com/participation/#pr-mr-details
> 
> I would appreciate it so then I can get credit for this PR for Hacktoberfest. Thanks :)

Done 😊

**Pull request merged**
